// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type HttpResponse struct {
	Code       int32       `json:"code"`       // 状态码
	Msg        string      `json:"msg"`        // 提示信息
	Data       interface{} `json:"data"`       // 数据
	Time       int64       `json:"time"`       // 时间戳
	RequestUrl string      `json:"requestUrl"` // 请求地址
}

type LoginReq struct {
	Email       string `json:"email"`
	Password    string `json:"password"`
	CaptcahCode string `json:"captcahCode"`
	CaptcahKey  string `json:"captcahKey"`
}

type LoginResp struct {
	Token  string `json:"token"`
	UserId string `json:"userId"`
}
