// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type HttpResponse struct {
	Code int32       `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data"`
}

type LoginReq struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	CaptcahCode string `json:"captcahCode"`
	CaptcahKey  string `json:"captcahKey"`
}

type LoginResp struct {
	Token  string `json:"token"`
	UserId string `json:"userId"`
}
