// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: pb/cos.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fids          []string               `protobuf:"bytes,1,rep,name=fids,proto3" json:"fids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImageIds) Reset() {
	*x = ImageIds{}
	mi := &file_pb_cos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageIds) ProtoMessage() {}

func (x *ImageIds) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageIds.ProtoReflect.Descriptor instead.
func (*ImageIds) Descriptor() ([]byte, []int) {
	return file_pb_cos_proto_rawDescGZIP(), []int{0}
}

func (x *ImageIds) GetFids() []string {
	if x != nil {
		return x.Fids
	}
	return nil
}

type ResourceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           string                 `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=fileType,proto3" json:"fileType,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceInfo) Reset() {
	*x = ResourceInfo{}
	mi := &file_pb_cos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceInfo) ProtoMessage() {}

func (x *ResourceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceInfo.ProtoReflect.Descriptor instead.
func (*ResourceInfo) Descriptor() ([]byte, []int) {
	return file_pb_cos_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceInfo) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

func (x *ResourceInfo) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ResourceInfo) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *ResourceInfo) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

type VideoInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           string                 `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoInfo) Reset() {
	*x = VideoInfo{}
	mi := &file_pb_cos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoInfo) ProtoMessage() {}

func (x *VideoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoInfo.ProtoReflect.Descriptor instead.
func (*VideoInfo) Descriptor() ([]byte, []int) {
	return file_pb_cos_proto_rawDescGZIP(), []int{2}
}

func (x *VideoInfo) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

type UploadClassCoverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`
	FileType      string                 `protobuf:"bytes,3,opt,name=fileType,proto3" json:"fileType,omitempty"`
	FileSize      int64                  `protobuf:"varint,4,opt,name=fileSize,proto3" json:"fileSize,omitempty"`
	DirectoryId   string                 `protobuf:"bytes,5,opt,name=directoryId,proto3" json:"directoryId,omitempty"`
	Md5           string                 `protobuf:"bytes,6,opt,name=md5,proto3" json:"md5,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClassCoverReq) Reset() {
	*x = UploadClassCoverReq{}
	mi := &file_pb_cos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClassCoverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClassCoverReq) ProtoMessage() {}

func (x *UploadClassCoverReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClassCoverReq.ProtoReflect.Descriptor instead.
func (*UploadClassCoverReq) Descriptor() ([]byte, []int) {
	return file_pb_cos_proto_rawDescGZIP(), []int{3}
}

func (x *UploadClassCoverReq) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UploadClassCoverReq) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *UploadClassCoverReq) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *UploadClassCoverReq) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadClassCoverReq) GetDirectoryId() string {
	if x != nil {
		return x.DirectoryId
	}
	return ""
}

func (x *UploadClassCoverReq) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

type UploadClassCoverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           string                 `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadClassCoverResp) Reset() {
	*x = UploadClassCoverResp{}
	mi := &file_pb_cos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadClassCoverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadClassCoverResp) ProtoMessage() {}

func (x *UploadClassCoverResp) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadClassCoverResp.ProtoReflect.Descriptor instead.
func (*UploadClassCoverResp) Descriptor() ([]byte, []int) {
	return file_pb_cos_proto_rawDescGZIP(), []int{4}
}

func (x *UploadClassCoverResp) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

type CopyObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fid           string                 `protobuf:"bytes,1,opt,name=fid,proto3" json:"fid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyObjectRequest) Reset() {
	*x = CopyObjectRequest{}
	mi := &file_pb_cos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyObjectRequest) ProtoMessage() {}

func (x *CopyObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyObjectRequest.ProtoReflect.Descriptor instead.
func (*CopyObjectRequest) Descriptor() ([]byte, []int) {
	return file_pb_cos_proto_rawDescGZIP(), []int{5}
}

func (x *CopyObjectRequest) GetFid() string {
	if x != nil {
		return x.Fid
	}
	return ""
}

type CopyObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewFid        string                 `protobuf:"bytes,1,opt,name=newFid,proto3" json:"newFid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyObjectResponse) Reset() {
	*x = CopyObjectResponse{}
	mi := &file_pb_cos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyObjectResponse) ProtoMessage() {}

func (x *CopyObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyObjectResponse.ProtoReflect.Descriptor instead.
func (*CopyObjectResponse) Descriptor() ([]byte, []int) {
	return file_pb_cos_proto_rawDescGZIP(), []int{6}
}

func (x *CopyObjectResponse) GetNewFid() string {
	if x != nil {
		return x.NewFid
	}
	return ""
}

type DeleteObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fids          []string               `protobuf:"bytes,1,rep,name=fids,proto3" json:"fids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectRequest) Reset() {
	*x = DeleteObjectRequest{}
	mi := &file_pb_cos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectRequest) ProtoMessage() {}

func (x *DeleteObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return file_pb_cos_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteObjectRequest) GetFids() []string {
	if x != nil {
		return x.Fids
	}
	return nil
}

type CosCommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CosCommonResponse) Reset() {
	*x = CosCommonResponse{}
	mi := &file_pb_cos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CosCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CosCommonResponse) ProtoMessage() {}

func (x *CosCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_cos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CosCommonResponse.ProtoReflect.Descriptor instead.
func (*CosCommonResponse) Descriptor() ([]byte, []int) {
	return file_pb_cos_proto_rawDescGZIP(), []int{8}
}

func (x *CosCommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_pb_cos_proto protoreflect.FileDescriptor

const file_pb_cos_proto_rawDesc = "" +
	"\n" +
	"\fpb/cos.proto\x12\x05proto\"\x1e\n" +
	"\bImageIds\x12\x12\n" +
	"\x04fids\x18\x01 \x03(\tR\x04fids\"t\n" +
	"\fResourceInfo\x12\x10\n" +
	"\x03fid\x18\x01 \x01(\tR\x03fid\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\x1a\n" +
	"\bfileType\x18\x03 \x01(\tR\bfileType\x12\x1a\n" +
	"\bfileSize\x18\x04 \x01(\x03R\bfileSize\"\x1d\n" +
	"\tVideoInfo\x12\x10\n" +
	"\x03fid\x18\x01 \x01(\tR\x03fid\"\xb7\x01\n" +
	"\x13UploadClassCoverReq\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1a\n" +
	"\bfileName\x18\x02 \x01(\tR\bfileName\x12\x1a\n" +
	"\bfileType\x18\x03 \x01(\tR\bfileType\x12\x1a\n" +
	"\bfileSize\x18\x04 \x01(\x03R\bfileSize\x12 \n" +
	"\vdirectoryId\x18\x05 \x01(\tR\vdirectoryId\x12\x10\n" +
	"\x03md5\x18\x06 \x01(\tR\x03md5\"(\n" +
	"\x14UploadClassCoverResp\x12\x10\n" +
	"\x03fid\x18\x01 \x01(\tR\x03fid\"%\n" +
	"\x11CopyObjectRequest\x12\x10\n" +
	"\x03fid\x18\x01 \x01(\tR\x03fid\",\n" +
	"\x12CopyObjectResponse\x12\x16\n" +
	"\x06newFid\x18\x01 \x01(\tR\x06newFid\")\n" +
	"\x13DeleteObjectRequest\x12\x12\n" +
	"\x04fids\x18\x01 \x03(\tR\x04fids\"-\n" +
	"\x11CosCommonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x99\x03\n" +
	"\x03Cos\x12D\n" +
	"\fDeleteObject\x12\x1a.proto.DeleteObjectRequest\x1a\x18.proto.CosCommonResponse\x12A\n" +
	"\n" +
	"CopyObject\x12\x18.proto.CopyObjectRequest\x1a\x19.proto.CopyObjectResponse\x12M\n" +
	"\x10UploadClassCover\x12\x1a.proto.UploadClassCoverReq\x1a\x1b.proto.UploadClassCoverResp(\x01\x12C\n" +
	"\x15AddVideoToLambdaQueue\x12\x10.proto.VideoInfo\x1a\x18.proto.CosCommonResponse\x127\n" +
	"\vGetFileInfo\x12\x13.proto.ResourceInfo\x1a\x13.proto.ResourceInfo\x12<\n" +
	"\x0fDeleteTaskImage\x12\x0f.proto.ImageIds\x1a\x18.proto.CosCommonResponseB\tZ\a.;protob\x06proto3"

var (
	file_pb_cos_proto_rawDescOnce sync.Once
	file_pb_cos_proto_rawDescData []byte
)

func file_pb_cos_proto_rawDescGZIP() []byte {
	file_pb_cos_proto_rawDescOnce.Do(func() {
		file_pb_cos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_cos_proto_rawDesc), len(file_pb_cos_proto_rawDesc)))
	})
	return file_pb_cos_proto_rawDescData
}

var file_pb_cos_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pb_cos_proto_goTypes = []any{
	(*ImageIds)(nil),             // 0: proto.ImageIds
	(*ResourceInfo)(nil),         // 1: proto.ResourceInfo
	(*VideoInfo)(nil),            // 2: proto.VideoInfo
	(*UploadClassCoverReq)(nil),  // 3: proto.UploadClassCoverReq
	(*UploadClassCoverResp)(nil), // 4: proto.UploadClassCoverResp
	(*CopyObjectRequest)(nil),    // 5: proto.CopyObjectRequest
	(*CopyObjectResponse)(nil),   // 6: proto.CopyObjectResponse
	(*DeleteObjectRequest)(nil),  // 7: proto.DeleteObjectRequest
	(*CosCommonResponse)(nil),    // 8: proto.CosCommonResponse
}
var file_pb_cos_proto_depIdxs = []int32{
	7, // 0: proto.Cos.DeleteObject:input_type -> proto.DeleteObjectRequest
	5, // 1: proto.Cos.CopyObject:input_type -> proto.CopyObjectRequest
	3, // 2: proto.Cos.UploadClassCover:input_type -> proto.UploadClassCoverReq
	2, // 3: proto.Cos.AddVideoToLambdaQueue:input_type -> proto.VideoInfo
	1, // 4: proto.Cos.GetFileInfo:input_type -> proto.ResourceInfo
	0, // 5: proto.Cos.DeleteTaskImage:input_type -> proto.ImageIds
	8, // 6: proto.Cos.DeleteObject:output_type -> proto.CosCommonResponse
	6, // 7: proto.Cos.CopyObject:output_type -> proto.CopyObjectResponse
	4, // 8: proto.Cos.UploadClassCover:output_type -> proto.UploadClassCoverResp
	8, // 9: proto.Cos.AddVideoToLambdaQueue:output_type -> proto.CosCommonResponse
	1, // 10: proto.Cos.GetFileInfo:output_type -> proto.ResourceInfo
	8, // 11: proto.Cos.DeleteTaskImage:output_type -> proto.CosCommonResponse
	6, // [6:12] is the sub-list for method output_type
	0, // [0:6] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_cos_proto_init() }
func file_pb_cos_proto_init() {
	if File_pb_cos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_cos_proto_rawDesc), len(file_pb_cos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_cos_proto_goTypes,
		DependencyIndexes: file_pb_cos_proto_depIdxs,
		MessageInfos:      file_pb_cos_proto_msgTypes,
	}.Build()
	File_pb_cos_proto = out.File
	file_pb_cos_proto_goTypes = nil
	file_pb_cos_proto_depIdxs = nil
}
