// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: pb/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Uid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Uid) Reset() {
	*x = Uid{}
	mi := &file_pb_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Uid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uid) ProtoMessage() {}

func (x *Uid) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uid.ProtoReflect.Descriptor instead.
func (*Uid) Descriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{0}
}

func (x *Uid) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_pb_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *UserInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type StudentInfos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Infos         []*StudentInfo         `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentInfos) Reset() {
	*x = StudentInfos{}
	mi := &file_pb_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentInfos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentInfos) ProtoMessage() {}

func (x *StudentInfos) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentInfos.ProtoReflect.Descriptor instead.
func (*StudentInfos) Descriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{2}
}

func (x *StudentInfos) GetInfos() []*StudentInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type StudentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	College       string                 `protobuf:"bytes,3,opt,name=college,proto3" json:"college,omitempty"`
	Major         string                 `protobuf:"bytes,4,opt,name=major,proto3" json:"major,omitempty"`
	Avatar        string                 `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentInfo) Reset() {
	*x = StudentInfo{}
	mi := &file_pb_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentInfo) ProtoMessage() {}

func (x *StudentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentInfo.ProtoReflect.Descriptor instead.
func (*StudentInfo) Descriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{3}
}

func (x *StudentInfo) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *StudentInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentInfo) GetCollege() string {
	if x != nil {
		return x.College
	}
	return ""
}

func (x *StudentInfo) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *StudentInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type AddStudentToClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStudentToClassRequest) Reset() {
	*x = AddStudentToClassRequest{}
	mi := &file_pb_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStudentToClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStudentToClassRequest) ProtoMessage() {}

func (x *AddStudentToClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStudentToClassRequest.ProtoReflect.Descriptor instead.
func (*AddStudentToClassRequest) Descriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{4}
}

func (x *AddStudentToClassRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *AddStudentToClassRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *AddStudentToClassRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UserCommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCommonResponse) Reset() {
	*x = UserCommonResponse{}
	mi := &file_pb_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCommonResponse) ProtoMessage() {}

func (x *UserCommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCommonResponse.ProtoReflect.Descriptor instead.
func (*UserCommonResponse) Descriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserCommonResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type StudentIds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []string               `protobuf:"bytes,1,rep,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentIds) Reset() {
	*x = StudentIds{}
	mi := &file_pb_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentIds) ProtoMessage() {}

func (x *StudentIds) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentIds.ProtoReflect.Descriptor instead.
func (*StudentIds) Descriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{6}
}

func (x *StudentIds) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

type ClassCids struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cids          []string               `protobuf:"bytes,1,rep,name=cids,proto3" json:"cids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassCids) Reset() {
	*x = ClassCids{}
	mi := &file_pb_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassCids) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassCids) ProtoMessage() {}

func (x *ClassCids) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassCids.ProtoReflect.Descriptor instead.
func (*ClassCids) Descriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{7}
}

func (x *ClassCids) GetCids() []string {
	if x != nil {
		return x.Cids
	}
	return nil
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`   // 文件内容
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"` // 文件名
	Cid           string                 `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`           // 课程id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_pb_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_pb_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_pb_user_proto_rawDescGZIP(), []int{8}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileChunk) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileChunk) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

var File_pb_user_proto protoreflect.FileDescriptor

const file_pb_user_proto_rawDesc = "" +
	"\n" +
	"\rpb/user.proto\x12\x05proto\"\x17\n" +
	"\x03Uid\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\"P\n" +
	"\bUserInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"8\n" +
	"\fStudentInfos\x12(\n" +
	"\x05infos\x18\x01 \x03(\v2\x12.proto.StudentInfoR\x05infos\"{\n" +
	"\vStudentInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acollege\x18\x03 \x01(\tR\acollege\x12\x14\n" +
	"\x05major\x18\x04 \x01(\tR\x05major\x12\x16\n" +
	"\x06avatar\x18\x05 \x01(\tR\x06avatar\"R\n" +
	"\x18AddStudentToClassRequest\x12\x10\n" +
	"\x03cid\x18\x01 \x01(\tR\x03cid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\".\n" +
	"\x12UserCommonResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\" \n" +
	"\n" +
	"StudentIds\x12\x12\n" +
	"\x04uids\x18\x01 \x03(\tR\x04uids\"\x1f\n" +
	"\tClassCids\x12\x12\n" +
	"\x04cids\x18\x01 \x03(\tR\x04cids\"S\n" +
	"\tFileChunk\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x10\n" +
	"\x03cid\x18\x03 \x01(\tR\x03cid2\xbb\x02\n" +
	"\x04user\x12O\n" +
	"\x11AddStudentToClass\x12\x1f.proto.AddStudentToClassRequest\x1a\x19.proto.UserCommonResponse\x12?\n" +
	"\x16BatchAddStudentToClass\x12\x10.proto.FileChunk\x1a\x11.proto.StudentIds(\x01\x129\n" +
	"\x0fGetStudentsInfo\x12\x11.proto.StudentIds\x1a\x13.proto.StudentInfos\x12:\n" +
	"\x13GetStudentClassList\x12\x11.proto.StudentIds\x1a\x10.proto.ClassCids\x12*\n" +
	"\vGetUserInfo\x12\n" +
	".proto.Uid\x1a\x0f.proto.UserInfoB\tZ\a.;protob\x06proto3"

var (
	file_pb_user_proto_rawDescOnce sync.Once
	file_pb_user_proto_rawDescData []byte
)

func file_pb_user_proto_rawDescGZIP() []byte {
	file_pb_user_proto_rawDescOnce.Do(func() {
		file_pb_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_user_proto_rawDesc), len(file_pb_user_proto_rawDesc)))
	})
	return file_pb_user_proto_rawDescData
}

var file_pb_user_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pb_user_proto_goTypes = []any{
	(*Uid)(nil),                      // 0: proto.Uid
	(*UserInfo)(nil),                 // 1: proto.UserInfo
	(*StudentInfos)(nil),             // 2: proto.StudentInfos
	(*StudentInfo)(nil),              // 3: proto.StudentInfo
	(*AddStudentToClassRequest)(nil), // 4: proto.AddStudentToClassRequest
	(*UserCommonResponse)(nil),       // 5: proto.UserCommonResponse
	(*StudentIds)(nil),               // 6: proto.StudentIds
	(*ClassCids)(nil),                // 7: proto.ClassCids
	(*FileChunk)(nil),                // 8: proto.FileChunk
}
var file_pb_user_proto_depIdxs = []int32{
	3, // 0: proto.StudentInfos.infos:type_name -> proto.StudentInfo
	4, // 1: proto.user.AddStudentToClass:input_type -> proto.AddStudentToClassRequest
	8, // 2: proto.user.BatchAddStudentToClass:input_type -> proto.FileChunk
	6, // 3: proto.user.GetStudentsInfo:input_type -> proto.StudentIds
	6, // 4: proto.user.GetStudentClassList:input_type -> proto.StudentIds
	0, // 5: proto.user.GetUserInfo:input_type -> proto.Uid
	5, // 6: proto.user.AddStudentToClass:output_type -> proto.UserCommonResponse
	6, // 7: proto.user.BatchAddStudentToClass:output_type -> proto.StudentIds
	2, // 8: proto.user.GetStudentsInfo:output_type -> proto.StudentInfos
	7, // 9: proto.user.GetStudentClassList:output_type -> proto.ClassCids
	1, // 10: proto.user.GetUserInfo:output_type -> proto.UserInfo
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_user_proto_init() }
func file_pb_user_proto_init() {
	if File_pb_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_user_proto_rawDesc), len(file_pb_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_user_proto_goTypes,
		DependencyIndexes: file_pb_user_proto_depIdxs,
		MessageInfos:      file_pb_user_proto_msgTypes,
	}.Build()
	File_pb_user_proto = out.File
	file_pb_user_proto_goTypes = nil
	file_pb_user_proto_depIdxs = nil
}
