// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.6

package types

type ApplyUploadRequest struct {
	ContentMd5    string `json:"contentMd5"`
	ContentLength string `json:"contentLength"`
	FileName      string `json:"fileName"`
}

type ApplyUploadResponse struct {
	Fid string `json:"fid"`
}

type HttpResponse struct {
	Code       int32       `json:"code"`       // 状态码
	Msg        string      `json:"msg"`        // 提示信息
	Data       interface{} `json:"data"`       // 数据
	Time       int64       `json:"time"`       // 时间戳
	RequestUrl string      `json:"requestUrl"` // 请求地址
}
