// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v3.19.4
// source: proto_repo/user.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddStudentToClassRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cid           string                 `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
	Uids          []string               `protobuf:"bytes,2,rep,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStudentToClassRequest) Reset() {
	*x = AddStudentToClassRequest{}
	mi := &file_proto_repo_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStudentToClassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStudentToClassRequest) ProtoMessage() {}

func (x *AddStudentToClassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStudentToClassRequest.ProtoReflect.Descriptor instead.
func (*AddStudentToClassRequest) Descriptor() ([]byte, []int) {
	return file_proto_repo_user_proto_rawDescGZIP(), []int{0}
}

func (x *AddStudentToClassRequest) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *AddStudentToClassRequest) GetUids() []string {
	if x != nil {
		return x.Uids
	}
	return nil
}

type AddStudentToClassResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddStudentToClassResponse) Reset() {
	*x = AddStudentToClassResponse{}
	mi := &file_proto_repo_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddStudentToClassResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddStudentToClassResponse) ProtoMessage() {}

func (x *AddStudentToClassResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_repo_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddStudentToClassResponse.ProtoReflect.Descriptor instead.
func (*AddStudentToClassResponse) Descriptor() ([]byte, []int) {
	return file_proto_repo_user_proto_rawDescGZIP(), []int{1}
}

func (x *AddStudentToClassResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_repo_user_proto protoreflect.FileDescriptor

var file_proto_repo_user_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x72, 0x65, 0x70, 0x6f, 0x2f, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40,
	0x0a, 0x18, 0x41, 0x64, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x75, 0x69, 0x64, 0x73,
	0x22, 0x35, 0x0a, 0x19, 0x41, 0x64, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x6f,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0x5e, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12,
	0x56, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64,
	0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x64,
	0x64, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_proto_repo_user_proto_rawDescOnce sync.Once
	file_proto_repo_user_proto_rawDescData []byte
)

func file_proto_repo_user_proto_rawDescGZIP() []byte {
	file_proto_repo_user_proto_rawDescOnce.Do(func() {
		file_proto_repo_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_repo_user_proto_rawDesc), len(file_proto_repo_user_proto_rawDesc)))
	})
	return file_proto_repo_user_proto_rawDescData
}

var file_proto_repo_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_repo_user_proto_goTypes = []any{
	(*AddStudentToClassRequest)(nil),  // 0: proto.AddStudentToClassRequest
	(*AddStudentToClassResponse)(nil), // 1: proto.AddStudentToClassResponse
}
var file_proto_repo_user_proto_depIdxs = []int32{
	0, // 0: proto.user.AddStudentToClass:input_type -> proto.AddStudentToClassRequest
	1, // 1: proto.user.AddStudentToClass:output_type -> proto.AddStudentToClassResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_repo_user_proto_init() }
func file_proto_repo_user_proto_init() {
	if File_proto_repo_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_repo_user_proto_rawDesc), len(file_proto_repo_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_repo_user_proto_goTypes,
		DependencyIndexes: file_proto_repo_user_proto_depIdxs,
		MessageInfos:      file_proto_repo_user_proto_msgTypes,
	}.Build()
	File_proto_repo_user_proto = out.File
	file_proto_repo_user_proto_goTypes = nil
	file_proto_repo_user_proto_depIdxs = nil
}
